// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kltcjeqdoobjbaqsdpfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtsdGNqZXFkb29iamJhcXNkcGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDYwODksImV4cCI6MjA2NTUyMjA4OX0.BM6XqQ8Rx4u8rQPOygy0CbQR_7TpJ5bz_QVua_aMK48";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);